#! /usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Street #330, Boston, MA 02111-1307,
# USA.

# This file is a part of Binc IMAP.

# Convert file entries to corresponding IMAPdir mailbox names.
# Use this script like this to add all IMAPdir entries to the
# subscription file:
#
# ls -a IMAPdir | toimapdir > IMAPdir/.bincimap-subscribed

while (<>) {
    unless (/^\\/ or /^\.$/ or /^\.\.$/) {
	chomp;
	s|([^\\])\.|$1/|g;
	s|\\\.|\.|g;
	s|\\\\|\\|g;
	s|^/|\.|;
	print; print "\n";
    }
}
